// Supabase Database Types
// This file will be generated by Supabase CLI in production

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          name: string;
          avatar_url?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          email: string;
          name: string;
          avatar_url?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          name?: string;
          avatar_url?: string;
          updated_at?: string;
        };
      };
      places: {
        Row: {
          id: string;
          name: string;
          type: string;
          description?: string;
          address?: string;
          latitude: number;
          longitude: number;
          rating?: number;
          price_level?: number;
          bts_station?: string;
          is_open?: boolean;
          opening_hours?: string;
          phone?: string;
          website?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          type: string;
          description?: string;
          address?: string;
          latitude: number;
          longitude: number;
          rating?: number;
          price_level?: number;
          bts_station?: string;
          is_open?: boolean;
          opening_hours?: string;
          phone?: string;
          website?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          type?: string;
          description?: string;
          address?: string;
          latitude?: number;
          longitude?: number;
          rating?: number;
          price_level?: number;
          bts_station?: string;
          is_open?: boolean;
          opening_hours?: string;
          phone?: string;
          website?: string;
          updated_at?: string;
        };
      };
      checkins: {
        Row: {
          id: string;
          user_id: string;
          place_id: string;
          rating?: number;
          notes?: string;
          photo_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          place_id: string;
          rating?: number;
          notes?: string;
          photo_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          place_id?: string;
          rating?: number;
          notes?: string;
          photo_count?: number;
          updated_at?: string;
        };
      };
      lists: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          description?: string;
          type: 'user' | 'auto';
          list_type: string;
          icon?: string;
          color?: string;
          is_public: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          description?: string;
          type?: 'user' | 'auto';
          list_type: string;
          icon?: string;
          color?: string;
          is_public?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          description?: string;
          type?: 'user' | 'auto';
          list_type?: string;
          icon?: string;
          color?: string;
          is_public?: boolean;
          updated_at?: string;
        };
      };
      list_places: {
        Row: {
          id: string;
          list_id: string;
          place_id: string;
          added_at: string;
        };
        Insert: {
          id?: string;
          list_id: string;
          place_id: string;
          added_at?: string;
        };
        Update: {
          id?: string;
          list_id?: string;
          place_id?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      place_type: 'restaurant' | 'cafe' | 'shopping' | 'temple' | 'park' | 'hotel' | 'attraction';
      list_type: 'favorites' | 'coffee' | 'date' | 'work' | 'want_to_try' | 'visited' | 'rated' | 'recent';
    };
  };
} 